### ISSUE TITLE
Add Tasks/Todo-Lists features

### ISSUE THREAD

**Issue by Davenchy** [M1-Elmasry/project_manager#10]
# Rules and permissions:
- A project member could create a task - no need for task owner/author field
- Edit task
- Label tasks
- Change task state according to predefined project states.
- Set/Unset a task as archived
- Add/Update/Delete check lists

# Types:

## Task:

- title: string
- body: string
- created_at: Date
- deadline?: Date
- state: string
- is_archived: boolean
- labels: string[]
- checklists: CheckList[]

## Checklist:

- title: string
- list: CheckListItem[]

## CheckListItem:

- content: string
- is_checked: boolean

## Progress:
- [x] Define Types
- [x] Define Routes
- [x] Complete TasksController
- [x] Complete ChecklistsController
- [x] Complete ChecklistItemsController
- [x] Middlewares
- [x] Fine-tuning and linking
- [x] Delete tasks/checklists/checklist_items
- [ ] Quick Manual Testing
- [x] Update workspace/project delete logic to delete tasks and their components too
- [ ] Write endpoint testing code.
